//
//  UpdaterService.swift
//  LocalMind
//
//  Sparkle auto-updates. The feed (SUFeedURL in Config/Info.plist) points at
//  the latest GitHub release's appcast.xml, generated by the release
//  workflow. Update integrity comes from the Developer ID code-signing chain
//  and, once an EdDSA key is configured (see docs/DISTRIBUTION.md), Sparkle
//  signatures too.
//
//  In keeping with PRIVACY.md: an update check is a plain HTTPS fetch of a
//  static XML file — no identifiers are sent, and Sparkle asks the user
//  before enabling automatic background checks.
//

import Foundation
import Sparkle

@MainActor
final class UpdaterService {
    static let shared = UpdaterService()

    private let controller: SPUStandardUpdaterController

    private init() {
        // startingUpdater: true schedules Sparkle's normal lifecycle (it
        // prompts the user once before any automatic checking begins). A
        // misconfigured feed logs and disables itself rather than crashing.
        controller = SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: nil,
            userDriverDelegate: nil
        )
    }

    /// User-initiated check with UI (menu item / settings button).
    func checkForUpdates() {
        controller.checkForUpdates(nil)
    }

    /// Whether a user-initiated check can start right now.
    var canCheckForUpdates: Bool {
        controller.updater.canCheckForUpdates
    }
}
